version: "2.3"

services:
  portainer:
    image: portainer/portainer
    mem_limit: 50m
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "9000:9000"

  message-queue:
    image: rmohr/activemq:5.14.3
    mem_limit: 600m
    expose:
      - "61616"       # the JMS port
      - "1883"        # the MQTT port
      - "5672"        # the AMQP port
    ports:
      - "8161:8161"   # the admin web UI
    networks:
      - jee7net

  datagrid-service:
    build: ./microservices/datagrid-service
    image: lreimer/datagrid-service:2.1
    mem_limit: 600m
    environment:
      - JAEGER_SERVICE_NAME=datagrid-service
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_REPORTER_LOG_SPANS=true
    volumes:
      - ./microservices/datagrid-service/src/main/hazelcast/hazelcast_default.xml:/opt/payara/config/hazelcast.xml
    expose:
      - "5701"        # the outbound Hazelcast port
      - "54327"       # the multicast Hazelcast port
    ports:
      - "18080:8080"  # the HTTP endpoint
    networks:
      - jee7net

  process-service:
    build: ./microservices/process-service
    image: lreimer/process-service:2.1
    mem_limit: 600m
    environment:
      - org_apache_deltaspike_ProjectStage=Development
      - JAEGER_SERVICE_NAME=process-service
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_REPORTER_LOG_SPANS=true
    volumes:
      - ./microservices/process-service/src/main/hazelcast/hazelcast_default.xml:/process-service/config/hazelcast.xml
    expose:
      - "5701"        # the outbound Hazelcast port
      - "54327"       # the multicast Hazelcast port
    ports:
      - "18081:8080"  # the HTTP endpoint
    depends_on:
      - message-queue
      - datagrid-service
      - process-db
    networks:
      - jee7net

  billing-service:
    build: ./microservices/billing-service
    image: lreimer/billing-service:2.1
    mem_limit: 600m
    environment:
      - org_apache_deltaspike_ProjectStage=Development
      - JAEGER_SERVICE_NAME=billing-service
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_REPORTER_LOG_SPANS=true
    volumes:
      - ./microservices/billing-service/src/main/hazelcast/hazelcast_default.xml:/billing-service/config/hazelcast.xml
    expose:
      - "5701"        # the outbound Hazelcast port
      - "54327"       # the multicast Hazelcast port
    ports:
      - "18082:8080"  # the HTTP endpoint
    depends_on:
      - message-queue
      - billing-db
    networks:
      - jee7net

  payment-service:
    build: ./microservices/payment-service
    image: lreimer/payment-service:2.1
    mem_limit: 600m
    environment:
      - org_apache_deltaspike_ProjectStage=Development
      - JAEGER_SERVICE_NAME=payment-service
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_REPORTER_LOG_SPANS=true
    volumes:
      - ./microservices/payment-service/src/main/hazelcast/hazelcast_default.xml:/payment-service/config/hazelcast.xml
    expose:
      - "5701"        # the outbound Hazelcast port
      - "54327"       # the multicast Hazelcast port
    ports:
      - "18083:8080"  # the HTTP endpoint
    depends_on:
      - message-queue
      - payment-db
    networks:
      - jee7net

  dashboard-service:
    build: ./microservices/dashboard-service
    image: lreimer/dashboard-service:1.2
    mem_limit: 600m
    environment:
      - JAEGER_SERVICE_NAME=dashboard-service
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_REPORTER_LOG_SPANS=true
    ports:
      - "18084:8080"  # the HTTP endpoint
    depends_on:
      - message-queue
    networks:
      - jee7net

  process-db:
    image: "postgres:9.6.3"
    mem_limit: 256m
    environment:
      - POSTGRES_USER=process
      - POSTGRES_PASSWORD=12qwasyx
    ports:
      - "15432:5432"
    networks:
      - jee7net

  billing-db:
    image: "postgres:9.6.3"
    mem_limit: 256m
    environment:
      - POSTGRES_USER=billing
      - POSTGRES_PASSWORD=12qwasyx
    ports:
      - "25432:5432"
    networks:
      - jee7net

  payment-db:
    image: "postgres:9.6.3"
    mem_limit: 256m
    environment:
      - POSTGRES_USER=payment
      - POSTGRES_PASSWORD=12qwasyx
    ports:
      - "35432:5432"
    networks:
      - jee7net

jaeger:
  image: "jaegertracing/all-in-one:1.5.0"
  mem_limit: 256m
  expose:
    - "14268"
    - "9411"
    - "5775/udp"
    - "6831/udp"
    - "6832/udp"
    - "5778"
  ports:
    - "16686:16686"
  networks:
    - jee7net

networks:
  jee7net:
    driver: bridge
